project_id = "bvrzbecprxbjnvkbusqg"

[functions.chat]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
